services:
  backend:
    container_name: lsm_backend
    image: ghcr.io/yellowsoar/live_stream_monitor:latest
    depends_on:
      - rabbitmq
    ports:
      - 0.0.0.0:8000:8000
    env_file:
      - ../.env

  rabbitmq:
    image: rabbitmq:3.12.13
    container_name: lsm_rabbitmq
