# Generated by Django 5.0.2 on 2024-02-27 08:10

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MonitoredVideo',
            fields=[
                (
                    'video_id',
                    models.CharField(
                        help_text='YouTube video id',
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    'live_status',
                    models.CharField(
                        default='',
                        help_text='Latest live status of the video.',
                        max_length=50,
                    ),
                ),
                (
                    'video_info',
                    models.JSONField(
                        default=dict,
                        help_text='Latest video info',
                    ),
                ),
                (
                    'check_duration',
                    models.IntegerField(
                        default=10,
                        help_text='The duration for video status checking in seconds.',
                    ),
                ),
                (
                    'check_timeout',
                    models.IntegerField(
                        default=10,
                        help_text='Timeout while checking the video in seconds.',
                    ),
                ),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
